### ISSUE TITLE
facing Internal Server Error Problem

### ISSUE THREAD

**Issue by reemuree** [SabBits/hls-proxifier#1]
python 
Framework = python , flask both try
Startup mode : UWSGI 
port : 5000

![image](https://github.com/SabBits/hls-proxifier/assets/129460830/f8f21da7-7294-474a-8cc5-710df64bf2d0)

**Comment by SabBits** [comment]
Could you please provide the command you are using to run it? 
Also, it's advisable to keep the **debug mode** enabled so that you can identify and troubleshoot any issues more effectively.

**Comment by reemuree** [comment]
i'm using apache server.Does it not work on Apache server?

**Comment by SabBits** [comment]
Yes, Apache Server does work. 

But I recommend deploying your application with a production-ready WSGI server like [Gunicorn](https://gunicorn.org/). This will ensure efficient handling of HTTP requests.

And to enhance your setup further, utilize a versatile reverse proxy such as [CaddyServer](https://caddyserver.com/) or [NGINX](https://www.nginx.com/). These tools can efficiently manage incoming requests, handle SSL termination, and offer additional features like load balancing if needed.
